# Generated by Django 4.0.2 on 2022-03-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Owner_Address', models.CharField(max_length=300)),
                ('rent', models.CharField(blank=True, max_length=200, null=True)),
                ('about_room', models.CharField(blank=True, max_length=300, null=True)),
                ('room_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='approved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_approve', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Fav_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner_Username', models.CharField(max_length=100)),
                ('Owner_Address', models.CharField(max_length=300)),
                ('rent', models.CharField(blank=True, max_length=200, null=True)),
                ('about_room', models.CharField(blank=True, max_length=300, null=True)),
                ('room_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Owner_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Mname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Address', models.CharField(max_length=300)),
                ('phone_number', models.IntegerField()),
                ('rent', models.CharField(blank=True, max_length=200, null=True)),
                ('about_room', models.CharField(blank=True, max_length=300, null=True)),
                ('room_img', models.ImageField(upload_to='rooms')),
                ('pass1', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Fname', models.CharField(max_length=100)),
                ('Mname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Address', models.CharField(max_length=300)),
                ('Pan_no', models.IntegerField()),
                ('Occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('Gender', models.CharField(max_length=20)),
                ('Dob', models.DateField()),
                ('phone_number', models.IntegerField()),
                ('pass1', models.CharField(max_length=20)),
            ],
        ),
    ]
