# Generated by Django 4.0.2 on 2022-03-04 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applied',
            table='app',
        ),
        migrations.AlterModelTable(
            name='approved',
            table='approved',
        ),
        migrations.AlterModelTable(
            name='fav_cart',
            table='fav',
        ),
        migrations.AlterModelTable(
            name='owner_reg',
            table='owner',
        ),
        migrations.AlterModelTable(
            name='user_reg',
            table='user',
        ),
    ]
