# Generated by Django 4.0.2 on 2022-03-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_applied_table_alter_approved_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_reg',
            name='room_img',
            field=models.URLField(),
        ),
    ]
