# Generated by Django 4.0.2 on 2022-03-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_home_loginlogs_passwordhistory_passwordresetlogs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='delete_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('pass1', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'del_acc',
            },
        ),
        migrations.AddField(
            model_name='home',
            name='owner_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.reg'),
        ),
    ]
